### ISSUE TITLE
position: 0 now makes model pushed to top?

### ISSUE THREAD

**Issue by USvER** [swanandp/acts_as_list#110]
After update i got weird issues with sorting.
After investigation i have found that new items got pushed to top, and not to bottom as described...
So model with position: 0 results into position: 1.
Is this new behaviour, or i have some issues in my code? Maybe with scope(i have scope on multiple fields) but how it relates to this?

**Comment by brendon** [comment]
Is this still a problem? Instead of a monkey patch it'd be good if we could fix it. New items should go at the bottom of the list by default. Have you tried removing the default value from that column?

**Comment by USvER** [comment]
Sorry, i'm not having access to that project anymore.

**Comment by brendon** [comment]
Ok, I'll close this. If someone can reproduce this with a failing test then we'll look into it.
