### ISSUE TITLE
Using insert_at with values with type String

### ISSUE THREAD

**Issue by vietqhoang** [swanandp/acts_as_list#117]
* Rails 4.0.4
* Ruby 2.1.1
* simple_form gem

For model `Foo`, inserting at say `position` utilizing strong parameters yields

    > Foo.insert_at(foo_params[:position])
    > ArgumentError: comparison of Fixnum with String failed

Parameters for my case are passed as String. To get it to insert, I must convert the parameter `position` to type Integer. I accomplished this in the `foo_params` method.

What's the feasibility of having the (String|Integer) => Integer conversion included in the insert_at method (and any other applicable method)?

**Comment by mcmegavolt** [comment]
:+1:

**Comment by brendon** [comment]
It could be feasible but not something any of us have time to work on. If you can provide a PR we can look at it from there. I'll close this for now though. I think it's reasonable to expect the position to be provided as an integer and for your code to be doing the conversion first.
