### ISSUE TITLE
Relationships with dependency:destroy cause ActiveRecord::RecordNotFound

### ISSUE THREAD

**Issue by skahlert** [swanandp/acts_as_list#118]
For more details see this page:
http://stackoverflow.com/questions/17695206/dependent-destroy-with-acts-as-tree-and-acts-as-list

**Comment by brendon** [comment]
https://github.com/swanandp/acts_as_list/pull/201 should have fixed this one. We `lock!` doesn't reload if the record is no longer persisted (i.e. it's new or deleted).

**Comment by jaredmoody** [comment]
I'm experiencing this issue on v0.9.9 - deleting the parent object that has `dependent: :destroy` on it or `parent.children.destroy_all`  gives me an `ActiveRecord::RecordNotFound` error.

**Comment by brendon** [comment]
Hi @jaredmoody, can you do a PR with a failing test case?
