### ISSUE TITLE
self.reload prone to error

### ISSUE THREAD

**Issue by alvinsj** [swanandp/acts_as_list#122]
this issue is referring to this [line of code](https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L445). 

I noticed active_record model is more or less destroy-safe. Meaning the children/parents of a model(e.g. dependent: destroy) can destroy the referring model, yet if model.destroy got called again before commit, it won't fail.

however, this self.reload like [below](https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L445) has failed the program and raising `RecordNotFound` error.

    before_destroy :reload_position
    def reload_position
      self.reload
    end

please let me know if i missed some code, or if anyone has a workaround for this.

**Comment by tfausak** [comment]
I have also been bit by this. I think the problem is that `acts_as_list` tries to `reload` a record even if it's not persisted. #46 introduced this behavior. Here is an example:

``` rb
require 'active_record' # 4.2.5
require 'acts_as_list' # 0.7.2

ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'

ActiveRecord::Schema.define do
  create_table :lists
  create_table :elements do |table|
    table.integer :list_id
    table.integer :position
  end
end

class List < ActiveRecord::Base
  has_many :elements
end

class Element < ActiveRecord::Base
  belongs_to :list
  acts_as_list scope: :list
end

list = List.new
x = list.elements.build
list.elements.each &:destroy
# ActiveRecord::RecordNotFound: Couldn't find Element without an ID
```

I can fix this issue by overriding `reload_position` on `Element`.

``` rb
def reload_position
  reload unless new_record?
end
```

**Comment by swelther** [comment]
Seems I'm hit by this bug too. Any news about the fix?

**Comment by brendon** [comment]
I'll look into this. What's the scenario in which one is destroying records not yet persisted in the database?

**Comment by swelther** [comment]
Not exactly. I try to destroy a record that has a `has_many` relationship with an acts_as_list model. And during the destroy I get the record not found error :cry:

It fails here:

acts_as_list-0.7.3/lib/acts_as_list/active_record/acts/list.rb:481

**Comment by swelther** [comment]
Oh wait, maybe it is our fault. We overwrite `destroy` in the related model and have an `dependent: :destroy` on the relation of the other model. It is a mess. I check this first :)

**Comment by brendon** [comment]
Haha, sounds like fun. Definitely sounds like an out-of-order destroy problem. I've had something similar with `ancestry` where I had to basically override the deletion routine to make sure it began deleting the leaves of the tree first and then upward rather than all at once in a non-deterministic way.

**Comment by swelther** [comment]
Yeah this was fun. Observer, circle dependent destroys and before_validation callbacks. But now it works and it was not acts_as_list fault :)

I'm glad I never used `ancestry`. I probably would go with a delete flag instead of actually destroying stuff to make my life easier :)

**Comment by brendon** [comment]
That's good to hear @swelther :) Glad you got your problem sorted.
