### ISSUE TITLE
How to exclude objects to be positioned?

### ISSUE THREAD

**Issue by axhamre** [swanandp/acts_as_list#125]
I have a Rails app where a Category has many Post.

`scope: :category` in the Post class is automatically giving position to posts withing the same category.

How could I exclude posts that has the attribute `published`set to `false` to be part of the positioning?

**Comment by axhamre** [comment]
Six years later, and I ask myself the same thing all over again. But this time around I feel more comfortable looking for the answer in the source code :)

This works great:

`acts_as_list scope: [:category_id, published: false]`

**Comment by brendon** [comment]
Haha! Great to see that feature worked for you :) It's certainly been much easier for me since learning to dive into gems and figure things out for myself. If you think this can be better documented, feel free to do a PR for documentation improvement :)
