### ISSUE TITLE
shuffle_positions_on_intermediate_items is creating problems

### ISSUE THREAD

**Issue by jordansinger** [swanandp/acts_as_list#134]
I have a case that is causing problems any time an object is updated.

Say I have an array of skills in an HTML form. Anytime I update the very first skill and send it to the server, it moves down 1 position. This is the query that is ran:

```
SQL (0.6ms)  UPDATE `skills` SET position = (position - 1) WHERE (`skills`.`resume_id` = 285 AND position > 0 AND position <= 1 AND id != '254')
```

The query above is moving the first item in the array of skills down one, which is very frustrating. Please help.

**Comment by jordansinger** [comment]
@swanandp I've actually found out when it triggers. So this bug only happens when you add 2 or more experiences, then reorder any of them. See here: https://www.dropbox.com/s/p8x3yiqhnlxszt1/Reorder%20bug%20demo.mov?dl=0

**Comment by jordansinger** [comment]
@swanandp Any idea? Thanks!

**Comment by chadmmills** [comment]
@jordansinger I was having the same issue while using the jQuery sortable library when sending the position in an ajax request which would serialize the ids into an array and then use the index of the array to save the position. This is incorrect because acts_as_lists seems to be one-based and the array index is zero based.  Assuming you are attempting the same, this is how I was able to fix it.

```ruby
params[:position_array].each_with_index do |id, index|
  Model.find(id).set_list_position(index + 1)
end
```

```javascript
$.post($(this).data('update-url'), $(this).sortable('serialize'))
```

**Comment by jordansinger** [comment]
@chadmmills This seems like the fix! Where did you put both of those respective blocks of code?

**Comment by chadmmills** [comment]
@jordansinger I put the params related piece in a separate controller method, only for  updating the position.

Check out Ryan Bates Railscast episode for a good tutorial on this functionality. http://railscasts.com/episodes/147-sortable-lists-revised
