### ISSUE TITLE
Problem when updating an position of array of AR objects.

### ISSUE THREAD

**Issue by murugan-r** [swanandp/acts_as_list#137]
I have an array of ActiveRecord Object and position. I need to update position of each AR object by iterating an array. 

Problem when updating first AR object , it changes the position of all other positions and so. I end up doing via update_column but i have callbacks that needs to be trigger.

Is there any way to update position without reordering an position of other AR object at the same time needs to trigger callbacks.

Note:: I am using acts_as_list (0.4.0)

**Comment by brendon** [comment]
There isn't a way as far as I know. This seems to be the standard way to go about it: https://github.com/swanandp/acts_as_list/issues/112#issuecomment-211008685

If you're just updating the position, then what callbacks do you need to run for that? :)

I'll close this for now, but feel free to comment further.
