### ISSUE TITLE
Changing scope is inconsistent based on add_new_at

### ISSUE THREAD

**Issue by k1w1** [swanandp/acts_as_list#138]
If `add_new_at` is set to `bottom` then items moved into a list because of scope changes are added at the requested position. If `add_new_at` is set to `top` then the items are always added at the top, regardless of the requested position.

This is important when you have a grid of items and want to support dragging between lists. In our use-case it makes more sense for `add_to_list_top` to work the same way as `add_to_list_bottom` and to respect the existing value of the position column. This would mean that truly new items would be added to the top, but items dragged between lists would stay in the position you dragged them to (because the position is already set).

**Comment by brendon** [comment]
Closing due to no one wanting to pursue this anymore. Could still be an obscure bug.
