### ISSUE TITLE
Rails 4.2 sanitize_sql_hash_for_conditions is deprecated, and will be removed in Rails 5.0

### ISSUE THREAD

**Issue by rexmadden** [swanandp/acts_as_list#144]
Upgraded to Rails 4.2 and there were a bunch of deprecation warnings about scopes. I'm using acts_as_list with Ancestry:

acts_as_list scope: [:project_id, :ancestry]

in Rails 5.0
         . (called from scope_condition at (eval):40)
/gems/activerecord-4.2.0/lib/active_record/sanitization.rb:90:in `sanitize_sql_hash_for_conditions'
(eval):40:in `scope_condition'
/gems/acts_as_list-0.5.0/lib/acts_as_list/active_record/acts/list.rb:318:in `bottom_item'
/gems/acts_as_list-0.5.0/lib/acts_as_list/active_record/acts/list.rb:312:in `bottom_position_in_list'
/gems/acts_as_list-0.5.0/lib/acts_as_list/active_record/acts/list.rb:300:in `add_to_list_bottom'
(eval):1:in `block in make_lambda'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:430:in `instance_exec'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:430:in `block in make_lambda'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_create_callbacks'
/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:306:in `_create_record'
/gems/activerecord-4.2.0/lib/active_record/timestamp.rb:57:in `_create_record'
/gems/activerecord-4.2.0/lib/active_record/persistence.rb:501:in `create_or_update'
/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:117:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:302:in `create_or_update'
/gems/activerecord-4.2.0/lib/active_record/persistence.rb:142:in `save!'
/gems/activerecord-4.2.0/lib/active_record/validations.rb:43:in `save!'
/gems/activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `block in save!'
/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
/gems/activerecord-4.2.0/lib/active_record/transactions.rb:291:in `save!'
/gems/activerecord-4.2.0/lib/active_record/persistence.rb:51:in `create!'

```ruby
          # Returns the bottom item
          def bottom_item(except = nil)
            conditions = scope_condition
            conditions = "#{conditions} AND #{self.class.primary_key} != #{self.class.connection.quote(except.id)}" if except
            acts_as_list_class.unscoped do
              acts_as_list_class.in_list.where(conditions).order("#{acts_as_list_class.table_name}.#{position_column} DESC").first
            end
          end

```

**Comment by fabn** [comment]
Closed in #140
