### ISSUE TITLE
insert_at doesn't seem to be working in ActiveRecord callback (Rails 4.2)

### ISSUE THREAD

**Issue by jasonsof** [swanandp/acts_as_list#150]
Trying to reorder a list inside of an after_create callback doesn't seem to do any reordering.  I created a little example with an rspec test in it.

https://github.com/jasonsof/acts-as-list-example

Is this normal, or am I doing something wrong here?

**Comment by brendon** [comment]
Hi Jason, There's an option you can pass to your acts_as_list call `:add_new_at => :top which should do what you're trying to do. It's not documented I don't think, but the code is here:

https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L38

**Comment by jasonsof** [comment]
Thanks Brendon, that option was exactly what I needed!

**Comment by brendon** [comment]
You're welcome :) I've found altering the current record in after_creates
is always a hassle. There always seems to be some unforeseen consequence.
Better to override the attribute setter or something like that instead (not
in this case though!).

Brendon Muir
