### ISSUE TITLE
Problem with reordering scoped list items

### ISSUE THREAD

**Issue by mcmegavolt** [swanandp/acts_as_list#154]
Can you help me guys to figure out how to reorder list items within scope, here my models:
```ruby
class Plan < ActiveRecord::Base
  # main association 
  has_many :items, -> { order("position ASC") },  dependent: :destroy
  # scoped associations
  has_many :draft_items, ->{ where(draft: true).order("position ASC") }
  has_many :final_items, ->{ where(draft: false).order("position ASC") }
end

class Item < ActiveRecord::Base
  belongs_to :plan
  acts_as_list scope: :plan
end
```

So, I need reorder list items within draft_items and final_items separately.

When I try to do this:

```ruby
plan.draft_items.find(3).insert_at(2)
```

It makes global **items** reordering outside my scope among all plan items.

How to resolve this? Thanks!

**Comment by swanandp** [comment]
@brendon @philippfranke Any chance you can take a look? I am going to be away for a while.

**Comment by brendon** [comment]
Hi @mcmegavolt, acts_as_list removes any existing scoping before applying its own scope:

https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L224

You'd have to utilise the `:scope =>` feature to scope your list. I think the scope can be something like:

`acts_as_list scope: :plan, :draft`

I hope that helps.

**Comment by mcmegavolt** [comment]
Thank you for responding!

I need sort items separately, with ```draft = true``` and ```draft = false``` but never for all plan items, only for those two cases.

```Plan``` has many ```Items``` but I want to sort item.draft: true/false separately.

I use jQuery for sorting two tables (Plan items where draft is true and false) on one page by dragging rows and send Ajax request to sort them.

So, I need to sort only items with darft = true or draft = false,

Please, explain me how to do that.

Thank you again!

**Comment by brendon** [comment]
Thanks @mcmegavolt, that will work well with the `scope` feature of acts_as_list. You're basically scoping the list on both the parent `:plan` and also the `:draft` column. So aal will maintain a separate list for each plan's draft and non-draft items. You might have to do `:scope => [:plan_id, :draft]' but just experiment. The scoping code is at the beginning of the aal source code and you can see how it tries to interpret different scope definitions.

**Comment by mcmegavolt** [comment]
Yes! ```:scope => [:plan_id, :draft]``` is working!
I sincerely thank you for your help!
You are doing a good job, thanks!

**Comment by brendon** [comment]
You're most welcome! :)

Brendon Muir
