### ISSUE TITLE
Inconsistent behaviour between Symbol and Array scopes

### ISSUE THREAD

**Issue by arnaudl** [swanandp/acts_as_list#155]
Hello,

When a symbol is passed to an association, [the scope column is inferred from the symbol](https://github.com/swanandp/acts_as_list/blob/f775b52af105f0bb470ce7facf96c0ec0c26d31d/lib/acts_as_list/active_record/acts/list.rb#L41):

```ruby
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  acts_as_list scope: :todo_list
end
```

```ruby
configuration[:scope] = "#{configuration[:scope]}_id".intern if configuration[:scope].is_a?(Symbol) && configuration[:scope].to_s !~ /_id$/
```

=> will give a scope on "todo_list_id"

If the scope is an array, the name passed as an argument is used, without adding the _id suffix:

```ruby
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  acts_as_list scope: [:todo_list]
end
```

=> the scope is now "todo_list". [The scope is then created with](https://github.com/swanandp/acts_as_list/blob/f775b52af105f0bb470ce7facf96c0ec0c26d31d/lib/acts_as_list/active_record/acts/list.rb#L57):

```ruby
memo[column.intern] = read_attribute(column.intern); memo
```

... but read_attribute on an association getter returns nil, which will give a query with `todo_list_id IS NULL`.

I don't know what the best solution would be... An easy fix could be to use `send(column.intern)` instead of `read_attribute(column.intern)`.

Another one would be to determine if the scope column is an association or not, with [reflect_on_association](http://api.rubyonrails.org/classes/ActiveRecord/Reflection/ClassMethods.html#method-i-reflect_on_association), which could also be used to determine the foreign key instead of just appending _id to the name.

**Comment by brendon** [comment]
Hi @arnaudl, is this still an issue for you? I think this behaviour is consistent right back to the early days of `acts_as_list`. The scope feature has always been a bit of a mind job.

Unfortunately we don't have time to work on new features like this at the moment. If you'd like to provide a PR with some tests then we'll definitely work with you on it, but otherwise I'm going to close this for now. :)
