### ISSUE TITLE
Fill old data with position numbers

### ISSUE THREAD

**Issue by avdept** [swanandp/acts_as_list#156]
Is there any ready to use rake task or script, that would populate data that has been created without using this gem with some position numbers?

**Comment by giovannibonetti** [comment]
In your migration you can do something like this, assuming:
- you are using Postgres
- the order you want to start with is alphabetical (column "name")

```ruby
execute <<-SQL
  UPDATE objects
    SET position = subquery.pos
    FROM (
      SELECT id, row_number() over (partition by scope_id ORDER BY name ASC) AS pos
      FROM objects
    ) AS subquery
    WHERE objects.id = subquery.id;
SQL
```
