### ISSUE TITLE
Release a new gem version

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#160]
Hi Swanand, I've just bumped into the STI problem introduced in the last gem version. I think we should release a new gem version given the bug is pretty insidious (took me a while to figure out what was going wrong).

Sound good? :)

**Comment by swanandp** [comment]
Sure :+1:

**Comment by swanandp** [comment]
Do you have a test case we can add to the suite ?

**Comment by brendon** [comment]
I think the bug fix already has updated test cases to catch the regression that was introduced, so we just need to release the gem version unless you think it needs more coverage. It looks good to me though, and I've tried the master branch out in my app and it fixed the problem. :)

**Comment by swanandp** [comment]
Great, then. :shipit:

**Comment by brendon** [comment]
Thanks Swanand, just released 0.7.0.
