### ISSUE TITLE
Model.find being called twice with acts_as_list on destroy

### ISSUE THREAD

**Issue by npearson72** [swanandp/acts_as_list#161]
I have a Category model that uses acts_as_list.

In my controller, I'm calling `Category.find(params[:id])`

When I try to run my tests, for some reason `.find` is called twice.

When I remove the `acts_as_list` method from my Category model, it works fine.

For more context, please refer to my rspec mocks issue:

https://github.com/rspec/rspec-mocks/issues/939

Any ideas?

**Comment by npearson72** [comment]
Just following up. Seems there's a `destroy` callback that's triggering another find. When I call `delete` this problem does not happen.

Does this help?

**Comment by npearson72** [comment]
Seems this is being caused in:

`lib/acts_as_list/active_record/acts/list.rb`

Line 477

`#reload_position` is calling `#reload`

Does this need to call `find`? Seems odd.

**Comment by swanandp** [comment]
@npearson72 `ActiveRecord::Base#reload` will call `find` internally.

As a general advice, I'd recommend changing your test slightly to assert that `find` is called *at least* once, instead of *exactly* once. Otherwise you are testing implementation, and not behaviour.

**Comment by npearson72** [comment]
Ok, thanks. But are you saying this isn't an issue?

**Comment by Albin-trialbee** [comment]
This is not an issue, it is necessary in order to be certain that the positions are correct after the destroy is done.

**Comment by brendon** [comment]
That's correct. We now use `lock!` instead but the outcome is the same.
