### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by Albin-Willman** [swanandp/acts_as_list#162]
I forked the repo today and figured I would like to get to know the code since we are evaluating if we might want to use this gem.

How ever I am unable to get the tests to run. I get the following error when I run `bundle exec rake test`:

```
active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `enum' for #<Class:0x007f8dec28bfa0> (NoMethodError)
	from /Users/Albin/Kod/acts_as_list/test/test_list.rb:80:in `<class:EnumArrayScopeListMixin>'
	from /Users/Albin/Kod/acts_as_list/test/test_list.rb:78:in `<top (required)>'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
	from /Users/Albin/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
```

Does any one recognise this?
So far I tried it with ruby 1.9.3, 2.1 and 2.2 and all have yielded the same output.

My debugging up to this point.

* The error occurs in `test_list.rb` when trying to create the class `EnumArrayScopeListMixin < Mixin`.
* I have established that the tests think Im running rails 4 (which I am)
* The class where the error is thrown inherits from `ActiveRecord::Base` via `Mixin`

Is there any more information that might be help full if I provided?

I don't have much experience with minitest so it might be something super obvious I am missing.

**Comment by Albin-trialbee** [comment]
Found out what the problem was. I was running `activerecord-4.0.13`. `enum` was defined in rails 4.1

Should I leave this open?

**Comment by swanandp** [comment]
@Albin-Willman Yeah, this has been a known issue with the test-suite, I am okay to let it depend on 4.1.
