### ISSUE TITLE
ArgumentError (comparison of String with 1 failed): error 

### ISSUE THREAD

**Issue by pradeekyahvi** [swanandp/acts_as_list#164]
I am getting error in acts_as_list v 0.7.2 like

Parameters: {"utf8"=>"✓", "authenticity_token"=>"VB82KaxZpXwkpytX6tI0BMhFMvAZ3KeIsjpLKC9VZf/LL1P1IqzHTQNeEb+Az5WVbztGA8IbftN3Gqqe/MNTjg==", "section"=>{"page_id"=>"2", "name"=>"werewrewrewr", "position"=>"1", "visible"=>"1", "content_type"=>"text", "content"=>"ASDASDASD"}, "commit"=>"Create Section", "page_id"=>"2"}
  Page Load (0.2ms)  SELECT  `pages`.* FROM `pages` WHERE `pages`.`id` = 2 LIMIT 1
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.6ms)

ArgumentError (comparison of String with 1 failed):

But this error is not showing in v 0.3.0 , please help me on this why this error showing in v 0.7.2

**Comment by brendon** [comment]
Hi @pradeekyahvi, can you provide more of a stack trace? We need to know where the error is occurring.

**Comment by pradeekyahvi** [comment]
acts_as_list (0.7.2) lib/acts_as_list/active_record/acts/list.rb:484:in `<'
acts_as_list (0.7.2) lib/acts_as_list/active_record/acts/list.rb:484:in `check_top_position'
activesupport (4.2.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_validation_callbacks'
activemodel (4.2.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (4.2.1) lib/active_model/validations.rb:334:in `valid?'
activerecord (4.2.1) lib/active_record/validations.rb:58:in `valid?'
activerecord (4.2.1) lib/active_record/validations.rb:83:in `perform_validations'
activerecord (4.2.1) lib/active_record/validations.rb:37:in `save'
activerecord (4.2.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
activerecord (4.2.1) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.1) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
activerecord (4.2.1) lib/active_record/transactions.rb:286:in `block in save'
activerecord (4.2.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
activerecord (4.2.1) lib/active_record/transactions.rb:285:in `save'
app/controllers/sections_controller.rb:25:in `create'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
rack (1.6.1) lib/rack/content_length.rb:15:in `call'
rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
/home/pradeek/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/pradeek/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/pradeek/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

**Comment by brendon** [comment]
Ok so it's this line:

`if send(position_column) && !default_position? && send(position_column) <
acts_as_list_top`

I'm going to guess that you have some configuration around `:top_of_list`
or `:column` that might no longer be working. Can you share your
acts_as_list declaration, and if you're overriding `position_column` or
`acts_as_list_top` in your class?

Cheers,


Brendon Muir

**Comment by pradeekyahvi** [comment]
please check my source code at 

https://github.com/pradeekyahvi/simple_cms/blob/master/app/models/subject.rb
https://github.com/pradeekyahvi/simple_cms/blob/master/app/models/page.rb
https://github.com/pradeekyahvi/simple_cms/blob/master/app/models/section.rb

**Comment by brendon** [comment]
Perhaps it's your touch callbacks? You could instead use `:touch => true` on the belongs_to relationship.

Otherwise I'm not sure. I see in your code you're explicitly setting a position in the parameters. Normally you'd let `aal` handle that. Try not doing that and see if it makes a difference.

**Comment by amronrails** [comment]
I had the same issue before and then I realized that position wasn't an integer variable. may be you have the same issue.

**Comment by fabn** [comment]
The issue is explained by @amronrails comment, `position` column is a string thus the error.

See https://github.com/pradeekyahvi/simple_cms/blob/master/db/schema.rb#L60

**Comment by pradeekyahvi** [comment]
Thanks Guys.
