### ISSUE TITLE
Support rails 5 ?

### ISSUE THREAD

**Issue by bublik** [swanandp/acts_as_list#186]

**Comment by brendon** [comment]
There are a few open issues around Rails 5 compatibility. Would you like to reference them into this issue?

**Comment by Darkside73** [comment]
+1

**Comment by brendon** [comment]
https://github.com/swanandp/acts_as_list/issues/191

**Comment by brendon** [comment]
https://github.com/swanandp/acts_as_list/issues/194

**Comment by brendon** [comment]
I've started by including tests for Rails 5 beta 3: https://github.com/swanandp/acts_as_list/pull/203

**Comment by brendon** [comment]
I've fixed all the test problems etc... so I'm fairly certain we now have Rails 5 support. Please comment here if you find anything else.

**Comment by dsandstrom** [comment]
Can you publish a new version that includes Rails 5 support?

**Comment by brendon** [comment]
Sorted :) 0.7.5 is the version you want. This is tested against Rails 5 RC2.
