### ISSUE TITLE
Remove or tone down hound & future of acts_as_list

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#189]
@swanandp, @fabn I'm thinking we should remove hound until the code has been properly fixed to adhere to the rules. It seems to be putting people off when they do a pull request.

I'm also wondering if we could have a discussion about the future maintenance of this gem. It's really one of two options out there for this problem. The other is `ranked-model` and that hasn't seen any love for quite some time.

There's quite a few problems with this gem as it stands (many edge cases, and many open issues and pull requests). I don't feel confident tackling them all by myself, but maybe we could schedule a bit of a session to fix some of these problems up?

**Comment by swanandp** [comment]
Yup, agreed. Until configured properly let's remove hound, the default settings are too annoying.

**Comment by swanandp** [comment]
I did one round of clean up some time ago, on issues and PRs - but I agree with you, this needs some more efforts.

**Comment by brendon** [comment]
Thanks @swanandp :) Is removing hound something you have to do on your end? I couldn't figure out how it was linked :)

Perhaps we could schedule a day of work on the gem? Of course there are time zones etc... and I'm not sure what your schedule is like, but I could put away a day at some point to dedicate to a cleanup/refactor. I guess the top priority is Rails 5 compatibility.

**Comment by fabn** [comment]
@brendon I don't control Hound, but I think it's now gone.

For the other question, I love to work for open source projects however, as majority of us, I do that in my spare time and it's always a scarce resource.

I agree that this gem needs more efforts to work past PR and issues but I don't think that I can schedule a fixed time to do that.

**Comment by brendon** [comment]
Thanks @fabn, I totally understand. I think we're all in that boat :) At least Hound is gone now :D

**Comment by swanandp** [comment]
I removed HoundCI; I like it, but not on default settings.

**Comment by swanandp** [comment]
@brendon About the time - like @fabn said, I wish I could set a day apart and hit this ball out of the park, but that's not gonna happen. :( So we're back to base-by-base.

**Comment by brendon** [comment]
Haha, yea. It was just spamming as it was. Did you have any thoughts on the scope change detection in after_ callbacks for https://github.com/swanandp/acts_as_list/pull/188 ?

**Comment by swanandp** [comment]
I haven't yet gone through the entire thread, but looking now.
