### ISSUE TITLE
DEPRECATION WARNING: Passing string to define callback on Rails 5 beta 3

### ISSUE THREAD

**Issue by arogachev** [swanandp/acts_as_list#191]
From logs:

> DEPRECATION WARNING: Passing string to define callback is deprecated and will be removed in Rails 5.1 without replacement.

Then it references to model to line where `acts_as_list` declared. I use simple definition, without additional options.

I'm using Rails 5 beta 3.

**Comment by brendon** [comment]
I've created a branch with the fix (I think): https://github.com/swanandp/acts_as_list/pull/192

Can you try using that branch and let me know if you still get the warning?

**Comment by brendon** [comment]
Fixed by #192.
