### ISSUE TITLE
Ouch, we got a mention!

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#222]
http://olivierlacan.com/posts/the-upgrade-trails @olivierlacan

At least we still support Rails 3.2 :P

**Comment by olivierlacan** [comment]
Props for keep the gem up-to-date. Otherwise I would have suffered a lot more. 😉

**Comment by olivierlacan** [comment]
Also so much love from me for that wonderful [CHANGELOG](CHANGELOG.md). ❤️

**Comment by brendon** [comment]
Haha, the CHANGELOG generator is a bit of a beast, but it's better than nothing for sure :D These days I'm always left lost and confused and like a spoilt child if a dependency doesn't have a CHANGELOG.

**Comment by swanandp** [comment]
@olivierlacan Hope you have a better experience with acts_as_list in the future. @brendon has done a massive job of keeping us up to date with PRs and issues, we're in reasonable shape right now.

**Comment by brendon** [comment]
Thanks @swanandp :) It's been great to have been able to give a little back.
