### ISSUE TITLE
Break away from rails/acts_as_list

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#224]
I'd like to float the idea of breaking this repo away from `rails/acts_as_list` in terms of its being a fork of that repository.

Any thoughts on this? As far as my experience, I've created several erroneous pull requests against `rails/acts_as_list` as branches on `swanadp/acts_as_list` automatically refer to this when creating a PR. I suppose I should probably be using my own fork, but often collaboration is easier on the main repository.

**Comment by fabn** [comment]
This can be closed now.
