### ISSUE TITLE
highter_items returns items with the same position value

### ISSUE THREAD

**Issue by james-logan** [swanandp/acts_as_list#247]
Hey, this isn't really an issue, just a question.

Is there a reason this [line](https://github.com/swanandp/acts_as_list/blob/53d0bd408d6cb904ed78fcb904895c7bc994985f/lib/acts_as_list/active_record/acts/list.rb#L159) is using `<=` and not just `<`

In the off chance that something in the database has a position value that is equal to another item in the list, it will show up in the list of 'higher_items', won't it?

**Comment by brendon** [comment]
Hi @james-logan, This was added with the extra constraint on the next line that excludes the current record. The assumption is that there may be other records with the same position value, and we assume that those records are higher than this record.

This concept is utilised in the move up/down logic too from memory.

I hope that helps explain it :)

**Comment by brendon** [comment]
Feel free to close the issue or ask further questions :)
