### ISSUE TITLE
DEPRECATION WARNING on rails 5.0 as of acts_as_list 0.9

### ISSUE THREAD

**Issue by jhawthorn** [swanandp/acts_as_list#251]
Since upgrading to `0.9.0`, I've been seeing this deprecation error on Rails 5.0.1:

> DEPRECATION WARNING: #table_exists? currently checks both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only check tables. Use #data_source_exists? instead.

The call to table_exists was added [here](https://github.com/swanandp/acts_as_list/commit/cb8dfb58824af0663ad5e5b113bd36d69954ce05#diff-b505f02d01ecca97ea8fa490cc4ae70aR7)

**Comment by brendon** [comment]
Thanks @jhawthorn :)

@zharikovpro would you mind looking into how we can avoid this warning? Should just be a fork in the logic there I guess. I think we may have already done this elsewhere in the code already.

**Comment by zharikovpro** [comment]
@brendon yes, will take a look and prepare PR. Should be an easy fix.

**Comment by brendon** [comment]
All fixed @jhawthorn :) Thanks again @zharikovpro!
