### ISSUE TITLE
Getting invalid input syntax for uuid

### ISSUE THREAD

**Issue by musaffa** [swanandp/acts_as_list#253]
After upgrading from `0.8.2` to `0.9.1`, I'm getting this error:

```Shell
ActiveRecord::StatementInvalid (PG::InvalidTextRepresentation: ERROR:  invalid input syntax for uuid: "'2cf8a976-8fea-4157-8233-206bdcf20b28'"
```

`0.8.2` is generating this SQL which is correct:
```SQL
UPDATE "footnotes" SET "updated_at" = '2017-02-01 01:45:14.438527', "position" = ("footnotes"."position" + 1) WHERE "footnotes"."primary_legislation_id" = $1 AND ("footnotes"."position" >= 1) AND ("footnotes"."position" < 2 AND "footnotes".id != '551d4359-76c6-41b7-b779-6490a7d189fa')  [["primary_legislation_id", "256a693f-4b3f-4b81-90fc-6f17379f3ca7"]]
```
But `0.9.1` is generating the following SQL statement:
```SQL
UPDATE "footnotes" SET "position" = ("footnotes"."position" + 1), "updated_at" = '2017-02-01 01:33:33.649759' WHERE "footnotes"."primary_legislation_id" = $1 AND ("footnotes".id != '''2cf8a976-8fea-4157-8233-206bdcf20b28''') AND ("footnotes"."position" >= 1) AND ("footnotes"."position" < 2)  [["primary_legislation_id", "256a693f-4b3f-4b81-90fc-6f17379f3ca7"]]
```

The problem is at `"footnotes".id != uuid`.

**Comment by brendon** [comment]
A stack trace will be helpful here. We need to figure out what particular method is generating this query. Either we're not quoting things properly on our end, or your `uuid` gem or method is returning a troublesome string.

We changed the methods used to generate these queries in the latest release to be more hash/array based instead of string based.

eg:
```ruby
where("#{quoted_table_name}.#{self.class.primary_key} != ?", self.send(self.class.primary_key))
```

and

```ruby
conditions = except ? "#{quoted_table_name}.#{self.class.primary_key} != #{self.class.connection.quote(except.id)}" : {}
```

It's likely in the first example where we're relying on the database layer to quote the id or not.

**Comment by brendon** [comment]
Ideally I need the full stack trace not the SQL log as I want to know which particular arel method is causing the quoting.

Also check this out: http://ruby-journal.com/how-to-override-default-primary-key-id-in-rails/ it hints at rails not thinking that the id column is a string column. That should be where you dig next I think :)

**Comment by musaffa** [comment]
Unfortunately the full stack trace didn't yield very useful result. With some debugging, I've figured where the problem is. It is in this [line](https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L333) like you suggested: :
```Ruby
if avoid_id
  scope = scope.where("#{quoted_table_name}.#{self.class.primary_key} != ?", self.class.connection.quote(avoid_id))
end
```

`avoid_id` returns a string for uuid which is obvious because Rails cannot interpret `bdce4d08-fe0f-427b-bb2a-b7665a0dc4e8` as an integer. The article in the link, in fact, hints at Rails not thinking a string column an integer column, not the other way around.

I also tried this migration and it fails in the same way:
```Ruby
class CreateFootnotes < ActiveRecord::Migration
  def change
    create_table :footnotes, id: false do |t|
      t.uuid :id, primary_key: true, null: false, default: 'gen_random_uuid()'
      ....
    end
    ....
  end
end
```

A UUID cannot be represented as an integer. So the above active record query will always fail for UUID.

**Comment by musaffa** [comment]
In fact, any string based primary column will fail. A simple solution is to avoid quoting of any string type id values.

**Comment by brendon** [comment]
Thanks @musaffa for the debugging :) I've committed a change to master that should work for you. Can you test your code against master and let me know how you get on?

We were quoting the value because we used to string interpolate the query. Now no longer :)

**Comment by musaffa** [comment]
Now it's working. Thanks.

Will it work for integer types? I thought `quote` has been introduced as a [security feature](http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/Quoting.html#method-i-quote) against SQL injection attacks.

**Comment by brendon** [comment]
Glad to hear that.

We're using the array method to supply arguments ['some sql = ?', the_value] so Rails will quote / escape that automatically. I'll release a new version.
