### ISSUE TITLE
Is there way to specify the position when creating a resource?

### ISSUE THREAD

**Issue by jmuheim** [swanandp/acts_as_list#255]
Hello

I understand that I can move an existing resource using `insert_at`. But is there a way to specify the position of a resource right when creating it? Instead of adding it to the bottom, then moving it manually somewhere else?

Thank you.

**Comment by brendon** [comment]
Yep just pass the `:position` attribute (or whatever you called it) :)

**Comment by jmuheim** [comment]
Thank you!
