### ISSUE TITLE
Nil Polymorphic Association

### ISSUE THREAD

**Issue by juggy** [swanandp/acts_as_list#295]
Hello - 

I have this weird deadlock error that keeps coming back. I narrowed it down to acts_as_list. I am using the latest version.

Here is the definition

```
belongs_to :attachable, :polymorphic=>true
acts_as_list scope: [:attachable_id, :attachable_type, deleted_at: nil]
```

So far so good. But the rails app assigns the attachable in 2 steps (2 distinct controller actions): 
- create the file
- assign it to the attachable

Within the first, it uses the `acts_as_list_no_update` to avoid unnecessarily position the item against a nil attachable. 

My problem is within the assignment action, when I assign the File to the new attachable, it seems to reorder both the files within the new scope and the old scope (so attachable with a value and without a value). So it reorders the data when the scope is null and there can be a lot of files within that scope. This is how I get this deadlock error:

```
ActiveRecord::Deadlocked: PG::TRDeadlockDetected: ERROR: deadlock detected
DETAIL: Process 26279 waits for ShareLock on transaction 2492170; blocked by process 1338.
Process 1338 waits for ShareLock on transaction 2492172; blocked by process 26279.
HINT: See server log for query details.
CONTEXT: while updating tuple (126,14) in relation "core_files"
: UPDATE "core_files" SET "position" = ("core_files"."position" - 1), "updated_at" = '2018-01-08 17:49:14.517476' WHERE "core_files"."attachable_id" IS NULL AND "core_files"."attachable_type" IS NULL AND ("core_files"."position" > 0)
```

I would like to remove all positioning when the attachable is nil. Can I do that?

**Comment by brendon** [comment]
Hi @juggy, that's an interesting problem. Would you like to put together a failing test in our suite so we can get a better idea of where things are going wrong?

In the past I've overridden the scoping methods that are defined here: https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/scope_method_definer.rb

There are 3 of them. If you have complex scope situations you can write the methods yourself on your class and they'll be called instead.

Let me know how you get on :)

**Comment by brendon** [comment]
@juggy, are you wanting to progress this issue still? :)

**Comment by tosbourn** [comment]
Hey @brendon,

I'm finding myself in a similar position were creating my own scoping methods would make sense.

Is this all you'd need to do? I feel like I'm missing a step.

```
class Foo
  acts_as_list

  def scope_condition
    # code goes here
  end  

  def scope_changed?
   # more code
  end

    def destroyed_via_scope??
   # more code
  end
end
```
