### ISSUE TITLE
Cannot update record position when scoped to enum

### ISSUE THREAD

**Issue by Zmokizmoghi** [swanandp/acts_as_list#298]
```ruby
class Person < ApplicationRecord
	acts_as_list scope: :position, column: :sort
	
	enum position: {
    	director: 0,
    	teacher: 1
  	}
end
```
```ruby
Person.find(1).move_to_top
```
fails with 
```
NoMethodError: undefined method `position_id' for #<Person:0x007f88bd86af40>
```

Ruby version: 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
Rails version: 5.1.4
Sysytem: OS X 10.13.1

**Comment by brendon** [comment]
Hi @Zmokizmoghi, have a bit of a dig through the documentation. `acts_as_list` always appends `_id` to the scope if you supply a symbol. Supply an array instead [:position]. In saying this, I don't know how you'll get on with your current use case. Using the column name `position` for starters, and then it being an enum… I guess you can only try :)

**Comment by Zmokizmoghi** [comment]
Hi @brendon, thanks for explanations, and for this great gem also ;-)
