### ISSUE TITLE
Rails 5.2.0

### ISSUE THREAD

**Issue by davidwessman** [swanandp/acts_as_list#299]
When will the [changes](https://github.com/swanandp/acts_as_list/commit/28118105775acd3a967358a2c5f576a607165ab6) made to remove deprecations be released as a new version?

**Comment by brendon** [comment]
Hi @davidwessman, I'll drop a new gem today for you. Just setting up my new machine so trying to settle that first :)

**Comment by swanandp** [comment]
I was just thinking about this a few days ago.  We're not exactly following semantic versioning, I guess it's about time we did a 1.0 release.  

Maybe after one round of cleanup of higher impact existing issues & PRs we can do a 1.0 release.

For now, let's do a point release and move on.

**Comment by brendon** [comment]
Will do :) Unfortunately I've not been successful yet in getting a test suite running for Rails 5.2. It's probably to do with bundler but I'll work on getting that green before releasing.

**Comment by brendon** [comment]
Hi @davidwessman, I was wondering if you could take a look at: https://travis-ci.org/swanandp/acts_as_list/builds/339359508

For some reason Rails 5.2 is failing across all rubies though locally I can get it to work fine. If you have any ideas I'd love to hear them :) The error message doesn't give much to go on :(

**Comment by brendon** [comment]
ok, I've got it all passing except for jruby. Just pending @swanandp's decision on dropping official support for that platform...

**Comment by davidwessman** [comment]
@brendon Sorry I did not see this before - great that you got it to work! :)

**Comment by davidwessman** [comment]
Do you need help with anything else? @brendon @swanandp

**Comment by brendon** [comment]
Hi @davidwessman, just waiting on @swanandp to get the jruby test suite fixed :)

**Comment by swanandp** [comment]
I looked into that -- it's a massive dependency versioning issue. We should add a note in README about currently broken JRuby support and move on for now. I will try to fix the problems in the coming days.

**Comment by brendon** [comment]
Thanks @swanandp, sounds good.

**Comment by brendon** [comment]
I'll do a point release now.
