### ISSUE TITLE
Dropping jruby support

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#300]
Hi @swanandp, I was wondering what you thought about dropping official `jruby` support? We've always had trouble keeping the test suite working with it and it's often broken outside of our control.

Just a thought :) I hope you had a great Christmas break and an easy start back into work :D

**Comment by swanandp** [comment]
@brendon I will take a shot at debugging and fixing JRuby build, until then let's add a warning and continue supporting it.

**Comment by swanandp** [comment]
Closing this for now, because I do want to keep supporting `jruby`.  If it's completely outside our control, we can let someone in the jruby team know about it, they are usually good about these things.

**Comment by brendon** [comment]
Thanks @swanandp. I'm happy for you to tackle that one. It appears there is some code failures relating to some recent PR's and a LOT of warnings. :)
