### ISSUE TITLE
Switching to Semaphore

### ISSUE THREAD

**Issue by brendon** [swanandp/acts_as_list#301]
Hi @swanandp, I was wondering what you thought about switching to Semaphore CI? I use it for my personal projects and it's really good. I nice feature is easy access to SSH sessions for build so one can debug them (not so easy on Travis with public projects). They're free for OS projects too.

**Comment by brendon** [comment]
Further to this, I'll need you to do the following steps @swanandp as I don't have access to the settings area:

> If Semaphore is able to list only repos owned by your personal Github account, than I'd suggest following these steps
> 
> 1. Granting access for Semaphore on Github
> 
> Firstly, it is necessary to request organization approval for Semaphore as a third party application on Github. You should be able to do this by visiting the this page (https://github.com/settings/connections/applications/eb03bb1b0fb539ed83ae).
> 
> 2. Adding project when its repo is owned by Github organization
> 
> Additionally, it is needed that Github user associated with Semaphore acc (project creator) - has admin access on GH. 
> Unfortunately, in the past GitHub didn't allow us to make a read_only deploy key via their API. The deploy key is needed so that Semaphore can fetch repository in order to run builds.
> 
> We are aware that this has changed on Github, and we plan to improve Semaphore on this matter in order to fetch repository without write access.

If you're keen to go ahead with this let me know :D

**Comment by swanandp** [comment]
I don't mind, really. We just need a build pipeline.

**Comment by swanandp** [comment]
Reading up on them right now.

**Comment by swanandp** [comment]
Does Semaphore offer anything over Travis apart from easy SSH access?  Travis has debug mode for that: https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by brendon** [comment]
It does, but I can't access it as it's a public repository. It requires you to do some convoluted `curl` API call with a key before it can be accessed.

I find it more responsive than travis in terms of build speed but that may differ for this project.

Up to you :)

**Comment by swanandp** [comment]
I think a change is unwarranted right now, so let's stick to Travis.  But if in future we get trouble debugging anything, we can make the switch.

By the way, currently Travis does a whole matrix of builds, Ruby, Rails and DB versions -- I am guessing Semaphore supports all that.

**Comment by brendon** [comment]
Good point. All I've ever seen is configuration for a specific ruby version per build. Perhaps travis is more advanced in this respect but I haven't dug into the semaphore side on this and there's no point in doing that at the moment :)

I'm happy with your decision :) Perhaps while you're debugging the jruby tests, have a go at the SSH thing and if you can get it to work, can you share the command/key with me so I can also do that if needed in the future?

**Comment by n-rodriguez** [comment]
@swanandp where did you see that SemaphoreCI supports matrix of builds?

**Comment by strika** [comment]
Semaphore perhaps doesn't support matrix of builds as elegantly as Travis does, but it's really easy to set up. All you need to do is create a job for each Ruby (or any other platform) version that you want to execute tests on, setup the version and execute your test commands. It's really straightforward. Note that Semaphore allows you to add as many jobs as you want, even if you can run only one job at the time. They will be executed sequentially.

**Comment by n-rodriguez** [comment]
Ok. Thank you!

**Comment by brendon** [comment]
Lol, how did this issue get so much viewership? I'm confused :)

**Comment by swanandp** [comment]
If I'm not mistaken, Striva here is quite a semaphore fan :)

**Comment by brendon** [comment]
Haha! Yes, I just saw his homepage :D I'm a fan too!

**Comment by strika** [comment]
I stumbled upon this issue by accident, since I use ActsAsList in a couple of projects. I was interested what you will choose, so I subscribed.

I worked on Semaphore till early 2016. And I still use Semaphore daily on several projects. So I am biased However, I tried to provide information in the comment, not to advertise.

As for the "likes" to my comment. I was surprised by that too. :)
