### ISSUE TITLE
Travis badge

### ISSUE THREAD

**Issue by n-rodriguez** [swanandp/acts_as_list#307]
Hi! It would be nice to have a Travis badge to show the build status.

Thank you!

**Comment by n-rodriguez** [comment]
Already here... https://github.com/swanandp/acts_as_list#build-status
Just had to scroll down ;)

**Comment by n-rodriguez** [comment]
Maybe it should be upper in the README?

**Comment by brendon** [comment]
Hi @n-rodriguez, all fixed now :)

**Comment by n-rodriguez** [comment]
Thank you! It's the first thing I look at when I'm using a gem ;)
