### ISSUE TITLE
`insert_at` saves invalid ActiveRecord objects

### ISSUE THREAD

**Issue by seanabrahams** [swanandp/acts_as_list#311]
If you construct an ActiveRecord object that doesn't pass validations and then call `insert_at` on it, acts_as_list will, in fact, save it to the database. It looks like this is intended behavior (https://github.com/swanandp/acts_as_list/blob/master/lib/acts_as_list/active_record/acts/list.rb#L213) but was surprising to me. Has this been discussed elsewhere? It seems like `insert_at` should fail when called on an invalid ActiveRecord object.

**Comment by brendon** [comment]
Hi @seanabrahams, thanks for bringing this up.

I think the `insert_at` method assumes the object is already persisted. Setting a position for a new (unsaved) object is as simple as setting the position attribute. `acts_as_list` will put the new object at that position when the object is saved.

We could perhaps look at preventing `insert_at` from working if the object isn't saved? It could even be rewritten as this perhaps?:

```
def set_list_position(new_position)
    update_attribute position_column, new_position
end
```

I haven't checked, but that would probably fail for a new object which is what we want.

Would you mind doing some digging on this and maybe putting together a PR? A failing test that passes with the update I mentioned above would also be good to have :)
