### ISSUE TITLE
Re-ordering at specific position

### ISSUE THREAD

**Issue by oyeanuj** [swanandp/acts_as_list#318]
Hi @brendon, quick question. Going through the docs, I couldn't find a method that would allow me to move an existing `list_item` to a new position and in effect, re-ordering rest of the items around it. It seems like `move_higher` or `move_lower` is the only thing available for that?

Am I missing something? Happy to PR the docs if there is some work around.

Thank you!

**Comment by brendon** [comment]
Hi @oyeanuj :) You can just set the position of the existing item and upon saving, it will move other items out of the way to make room. Generally you'd need to know the position of the item you'd like to insert your current item in front of. Hope that helps :)

**Comment by oyeanuj** [comment]
Got it, thanks so much!
