### ISSUE TITLE
Breaking changes in changelog

### ISSUE THREAD

**Issue by mainameiz** [swanandp/acts_as_list#341]
First of all, many thanks to contributors for making such a useful gem.

----

I would like to upgrade acts_as_list in my project. So first of all I visit [changelog](https://github.com/swanandp/acts_as_list/blob/master/CHANGELOG.md) page to investigate are there any breaking changes between my project version (0.9.1) and latest (0.9.17).
Unfortunately, there are no any notices about breaking changes. So I need to check every issue and pull request to find out what was changed/broken to safely upgrade the gem.
Could you consider to split the changelog into sections about new features, breaking changes, fixes, etc.
It seems to me it is more meaningful that just list of closed Issues/PRs.
It would help to quickly understood project changes between versions.

Thanks.

**Comment by mainameiz** [comment]
There is a great project about changelog best practices - https://keepachangelog.com/en/1.0.0/

**Comment by brendon** [comment]
Hi @mainameiz, thanks for the recommendations :) We currently use a changelog generator when releasing the gem; a kind of 'better than nothing' approach :) In saying that, hopefully you didn't encounter any breaking changes between those patch versions?

I've switched to a manually curated changelog again. Hopefully that helps people in the future :)
