### ISSUE TITLE
Mongoid support?

### ISSUE THREAD

**Issue by xanview** [swanandp/acts_as_list#52]
Would be great to have mongoid support in this :)

**Comment by dopudesign** [comment]
:+1:

**Comment by ricardobylife** [comment]
Yes, it would be awesome!

**Comment by koenpunt** [comment]
:+1:

**Comment by brendon** [comment]
We'd be happy to accept pull requests for this, but I don't think any of us has the time to develop this ourselves.

**Comment by koenpunt** [comment]
For now I've used https://github.com/pyromaniac/mongoid_orderable, but "one gem to rule them all" would be nice :)

**Comment by brendon** [comment]
Indeed :) I'll close this for now until someone wants to look into it.
