### ISSUE TITLE
Adding multiple creates strange ordering

### ISSUE THREAD

**Issue by vnguyen13** [swanandp/acts_as_list#55]
I'm now onto an object (license) that has_many of a certain object (progress_point). When I go to add multiple progress points to a license, it gives me mixed results. 

The first time I ran it, it gave my progress points "position" (called sequence) values of 1, 2, and 3. 

Second time, it ordered my items as 3, 2, 1.

The third time: 1, 3, 2. 

``` license.rb
class License < ActiveRecord::Base
  has_many :progress_points, :order => 'sequence'  
end
```

``` progress_point.rb
class ProgressPoint < ActiveRecord::Base
  belongs_to :license
  acts_as_list :column => :sequence, :scope => :license
end
```

Any ideas on why it would do this?

Also, this is how I'm doing the multiple add functionality if you're curious:
http://railscasts.com/episodes/197-nested-model-form-part-2

**Comment by brendon** [comment]
Closing this since there was no response from @vnguyen13.
