### ISSUE TITLE
Limiting the list size

### ISSUE THREAD

**Issue by randomizor** [swanandp/acts_as_list#61]
Would it be possible for there to be a way to limit the size of the list you can have? For example, if I have 100 items and try to set two items as item #100, the previously set one should go down to 99 (and this should trickle down the rest of the list)?

**Comment by brendon** [comment]
@swanandp, do you still want this as a future feature? It sounds a bit confusing to me. @randomizor, if you're still interested in this, could you explain it a bit more for me? :)

**Comment by swanandp** [comment]
@brendon No, I don't think so. This is a feature easily implemented in the application layer.

**Comment by swanandp** [comment]
Closing this now, but @randomizor feel free to add more to this, and we can talk about implementing this.
