### ISSUE TITLE
introduce Changelog file to quickly track changes

### ISSUE THREAD

**Issue by gogolok** [swanandp/acts_as_list#68]
It's hard to get a quick overview what has changed between version 0.1.8 and 0.1.9.
It would be nice to have a Changelog file.

**Comment by gogolok** [comment]
+1

**Comment by fabn** [comment]
@swanandp, you should really consider this. I've just updated my bundle and I got couple of tests failing and I don't know why. For the moment I've pinned aal to version 0.4.0, then I'll use github diff tool to find what's changed in range `0.4.0..0.6.0` but this is really painful.

Please take care of us :pray:

**Comment by swanandp** [comment]
Yup, I've been negligent on this so far.  But no more.  I'll see if I can do retrospective changelog.

**Comment by twelvelabs** [comment]
Please, please, please can you add a changelog? It's very tedious to have to use github's compare when updating apps w/ many dependencies.

**Comment by fabn** [comment]
Still no trace of changelog :cry: :cry:

**Comment by swanandp** [comment]
Sorry to disappoint you folks, this task is more tedious than it sounds. But I hope to wrap this up soon.

**Comment by fabn** [comment]
@swanandp I understand this is boring. However and quick and pretty easy fix would be to introduce a changelog file and start to use it right now for every important change (bugfix or new feature). Alternatively github releases feature is also good.

For past releases a github compare link would be enough (and easy to add), however this repo has no tags thus I can't submit a PR for that. Do you have some way to tag past releases?

**Comment by fabn** [comment]
You can tag past releases using [rubygems changelog](https://rubygems.org/gems/acts_as_list/versions) and for the future use [bundler gem tasks](https://github.com/bundler/bundler/blob/master/lib/bundler/gem_tasks.rb) to release the gem, in this way it will be automatically tagged and pushed to github.

**Comment by fabn** [comment]
Addressed by #177

**Comment by fabn** [comment]
Changelog file has been generated and it's now present in [master branch](https://github.com/swanandp/acts_as_list/blob/master/CHANGELOG.md)
