### ISSUE TITLE
move_higher/move_lower vs move_to_top/move_to_bottom act differently when item is already at top or bottom

### ISSUE THREAD

**Issue by dellch** [swanandp/acts_as_list#77]
If trying to move an item higher when it is already at the top of list (via move_higher), the return is nil (because it checks for higher_item).  But a move_to_top method only checks if the item is in_list?.  

(move_lower and move_to_bottom act the same way)

Shouldn't these two groups of methods either both return nil or both be successful?  Either would make sense, but the inconsistency doesn't make sense to me.

**Comment by brendon** [comment]
Hi @dellch, sorry for the very delayed response. Can you explain why this inconsistency is causing a problem? Is it because there is a bug in the outcome, or you'd just prefer a certain value returned?

**Comment by brendon** [comment]
@dellch, I'm closing this for now due to inactivity. Feel free to comment further if it's still a problem for you.
