### ISSUE TITLE
has_many :through or has_many_and_belongs_to_many support

### ISSUE THREAD

**Issue by LoveIsGrief** [swanandp/acts_as_list#86]
Hello,

I have not been able to work out how to make this work with a has_many :through association.

The easiest example I can think of is Playlists have many Songs and Songs belong to many Playlists. The position would have to be added to the intermediary table, because the position can be different in different playlists.

Does this gem support those associations?

**Comment by brendon** [comment]
I'm closing this for now due to inactivity.
