### ISSUE TITLE
Enhancement: Expose scope object

### ISSUE THREAD

**Issue by ludwigschubert** [swanandp/acts_as_list#97]
A `acts_as_list` object should expose its scope object/parent.

I'd love to patch and submit a pull request for this myself, but I'd like to discuss naming options, possible alternative solutions, and whether this is a sensible idea at all with you guys first.

### Workaround

I `#send` a substring of the scope name to the object
```ruby
object.send(object.scope_name[0..-3])
```

### Why?

This would allow to create awesome nested paths without needing to know about the scope explicitly, such as this reusable navigation snippet:
```ruby
link_to "Next Object", [:show, acts_as_list_object.scoped_to, acts_as_list_object.higher_item]
```

### Naming
Here are some possible names, feel free to chime in on how you like them:

* `scoped_to`
* `scope_object`
* `scope_parent`
* `parent` _imho ambiguous_

**Comment by brendon** [comment]
Hi @ludwigschubert, I'll close this off for now unless time has given you some new inspiration :)
